baseURL = 'https://awktatter.github.io/'
title = "Srinidhi's bleg"
theme = 'hugo-theme-yue'
languageCode = "en"
hasCJKLanguage = true
enableGitInfo = true

[params]
  dateFormat = "02-January-2006"
  description = "Welcome to my site! This is where I share my thoughts and articles."

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Brewed"
    url = "/brewed/"
    weight = 2
